### ISSUE TITLE
Use of agent needs to be replaced

### ISSUE THREAD

**Issue by InfiniteCoder** [sacOO7/160by2-SMS-API#1]
Using jaunt 1.2.7, a warning is generated
```
./M160by2.java:21: warning: agent is internal proprietary API and may be removed in a future release
import sun.management.resources.agent;
                               ^
1 warning
```
It needs to be replaced.

**Comment by sacOO7** [comment]
Hey there, try using latest version of jaunt, I think jaunt community releases new version every 1 month and earlier version gets outdated. It should work most probably.

**Comment by InfiniteCoder** [comment]
It works currently, but as the warning says, it might not work with future release of jaunt as they may remove agent.

**Comment by sacOO7** [comment]
Try to remove import statement,  I think API should work without it. Have you tried Way2SMS api. It's also better solution to send sms.

**Comment by InfiniteCoder** [comment]
Yes it works without the import as well. You should remove it from the code. I haven't tried your way2sms api yet.

**Comment by sacOO7** [comment]
Well remove import statment, and make new pull request. I have already merged your earlier request. If you have any further optimizations in mind, try to add them in pull request.

**Comment by InfiniteCoder** [comment]
Ok.
